export const fakeDb = [
  {
    name: "Anna Nowak",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Kraków",
    expectedContractType: "B2B",
    expectedSalary: "6500 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "Brak",
    id: 1,
  },
  {
    name: "Pawel Nowak",
    workPlacePreffer: "Biuro",
    prefferCity: "Warszawa",
    expectedContractType: "B2B",
    expectedSalary: "5500 zł",
    consentForFreeInternships: "Tak",
    commercialProgrammingExperience: "Brak",
    id: 2,
  },
  {
    name: "Patryk Keska",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Kraków",
    expectedContractType: "B2B",
    expectedSalary: "4200 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "Brak",
    id: 3,
  },
  {
    name: "Kinga Klimek",
    workPlacePreffer: "Biuro",
    prefferCity: "Kraków",
    expectedContractType: "UOP",
    expectedSalary: "8000 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "6 miesięcy",
    id: 4,
  },
  {
    name: "Pawel Zawada",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Lublin",
    expectedContractType: "UOP",
    expectedSalary: "9000 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "9 miesięcy",
    id: 5,
  },
  {
    name: "Julia Kowalska",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Kraków",
    expectedContractType: "B2B",
    expectedSalary: "3500 zł",
    consentForFreeInternships: "TAK",
    commercialProgrammingExperience: "Brak",
    id: 6,
  },
  {
    name: "Zbyszek Kwiatkowski",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Kraków",
    expectedContractType: "B2B",
    expectedSalary: "10000 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "Brak",
    id: 7,
  },
  {
    name: "Halina Smaga",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Kraków",
    expectedContractType: "B2B",
    expectedSalary: "7000 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "Brak",
    id: 8,
  },
  {
    name: "Karolina Keska",
    workPlacePreffer: "Zdalnie",
    prefferCity: "Kraków",
    expectedContractType: "B2B",
    expectedSalary: "8000 zł",
    consentForFreeInternships: "NIE",
    commercialProgrammingExperience: "6 miesięcy",
    id: 9,
  },
];
